### ISSUE TITLE
TeamDict mixup - reddit-boxscore-bot.py

### ISSUE THREAD

**Issue by joepope44** [f1uk3r/Some-Python-Scripts#1]
Hey bud, was admiring your code and noticed this mixup between Nets and Celtics in TeamDict. Cheers. 

"BKN": ["Brooklyn Nets", "02", "boston-celtics-", "http://np.reddit.com/r/bostonceltics", "1610612738"],
  "BOS": ["Boston Celtics", "17", "brooklyn-nets-","http://np.reddit.com/r/gonets", "1610612751"],

**Comment by f1uk3r** [comment]
Thank You, It is resolved now.
